version: '2.1'

services:
  # Aplicación
  app:
    image: tianon/true
      # Uncomment following lines and modify path for CUSTOM_CA
      # - /usr/local/share/ca-certificates/overcloud-cacert-mo.crt:/usr/local/share/ca-certificates/custom-ca.crt
    depends_on:
      downloader:
        condition: service_healthy
    volumes_from:
      - downloader
  # Nuevo servicio para descargar archivos
  downloader:
    image: alpine:latest # Usamos una imagen ligera de Alpine Linux
    command: >
      /bin/sh -c "apk add --no-cache curl unzip && \
                if [ ! -e /var/www/done ]; then \
                  curl -o /var/www/html.zip https://download.moodle.org/download.php/direct/stable401/moodle-4.1.11.zip && \
                  unzip -n /var/www/html.zip -d /var/www/ && \
                  rm /var/www/html.zip && \
                  touch /var/www/done; \
                fi && \
                  tail -f /dev/null"
    healthcheck:
      test: [ "CMD", "stat", "/var/www/done" ]
      interval: 10s
      timeout: 3s
      retries: 99999
    volumes:
      - ./${REPO_FOLDER}:${DOCUMENT_ROOT}
      - ./moodledata:${MOODLE_DATA}
  # Servicio de postgres:
  postgres:
    image: "moodledev/postgres:13-${PG_LOCALE}"
    build:
      context: ./postgres
      args:
        locale: "${PG_LOCALE}"
    expose:
      - "${PG_PORT}"
    # Uncomment following lines to expose postgres to host network
    # ports:
    #   - "${IP}:${PG_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db_dumps:/opt/db_dumps:z
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    depends_on:
      - app

  # Servicio de PHP-FPM
  php-fpm:
    image: "moodledev/php:8.0-fpm"
    build:
      context: ./php-fpm
      args:
        - DOCUMENT_ROOT
        - MY_TZ
    environment:
      - XDEBUG_CONFIG=idekey=PHPTEST
      - PHP_IDE_CONFIG=serverName=localhost
      - DOCUMENT_ROOT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - MOODLE_DATA
      - WWWROOT
      - WWW_PORT
      # Uncomment following lines and modify variable content for CUSTOM_CA
      # - |-
      #   CA_CERT=-----BEGIN CERTIFICATE-----
      #   REPLACE_CA_CONTENT
      #   -----END CERTIFICATE-----
    volumes_from:
      - app
    volumes:
      - ./log:/var/log/shared:z
    expose:
      - "${PHP_SOCKET}"
    links:
      - postgres
    depends_on:
      - postgres

  # Servicio de Apache2
  apache2:
    image: moodledev/apache2:2.4
    build:
      context: ./apache2
      args:
        DOCUMENT_ROOT: ${DOCUMENT_ROOT}
        PHP_SOCKET: php-fpm:${PHP_SOCKET}
        ALIAS_DOMAIN: ${ALIAS_DOMAIN}
    volumes_from:
      - app
    ports:
      - "${IP}:${WWW_PORT}:80"
    links:
      - php-fpm
      - postgres
    depends_on:
      - php-fpm

  # Cron para moodle
  cron:
    image: moodledev/php:8.0-fpm-cron
    build:
      context: ./cron
      args:
        DOCUMENT_ROOT: ${DOCUMENT_ROOT}
    volumes_from:
      - app
    depends_on:
      - apache2

  # Gestor de base de datos
  pgadmin:
    image: dpage/pgadmin4
    entrypoint: >
      /bin/sh -c "
      cp -f /pgadmin4/pgpass /var/lib/pgadmin/pgpass;
      chmod 600 /var/lib/pgadmin/pgpass;
      chown pgadmin:pgadmin /var/lib/pgadmin/pgpass;
      /entrypoint.sh
      "
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-ti@lucas.cl}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-lucas123}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "${IP}:5050:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json # preconfigured servers/connections
      - ./pgpass:/pgadmin4/pgpass
      - ./db_dumps:/root:z
    links:
      - postgres
    depends_on:
      - postgres
volumes:
  postgres-data:
    driver: "local"